#!/bin/bash
#read -p "Limit X : " b
#read -p "Limit Y : " c
b=63
c=19
clear 
tput cup 10 20
echo  "Bhavdeep Singh Sachdeva"
for(( a=2;$a<$b;a++ ))
do 
	tput cup 0 $a
	echo "_"
done

for(( a=1;$a<$c;a++ ))
do 
	tput cup $a 1
	echo "|"
done

for(( a=2;$a<$b;a++ ))
do 
	tput cup 18 $a
	echo "_"
done

for(( a=1;$a<$c;a++ ))
do 
	tput cup $a 64
	echo "|"
done
echo -e "\033[1;31m"
read -p "Press Enter to continue..."
reset
